### ISSUE TITLE
Reference for your methodology for neuroevolution of hyperparameters using DE?

### ISSUE THREAD

**Issue by bsolano** [OUStudent/EvolutionaryComputation#1]
Hi!

Does your methodology for neuroevolution of hyperparameters using DE ([example](https://github.com/OUStudent/EvolutionaryComputation/blob/master/EvolutionaryComputation/AutoML/examples/evolve_convolution_network_ciphar10_example.ipynb)) come from a specific study?  Do you have a reference for the methodology or is it your own creation?  I found papers like this https://arxiv.org/abs/1808.06661, among others.  However, your methodology although is simpler, it's also very effective.  I would like to reference it, but I don't know if I should reference a paper or your git.

Bests,

B.

**Comment by OUStudent** [comment]
> Hi!
> 
> Does your methodology for neuroevolution of hyperparameters using DE ([example](https://github.com/OUStudent/EvolutionaryComputation/blob/master/EvolutionaryComputation/AutoML/examples/evolve_convolution_network_ciphar10_example.ipynb)) come from a specific study? Do you have a reference for the methodology or is it your own creation? I found papers like this https://arxiv.org/abs/1808.06661, among others. However, your methodology although is simpler, it's also very effective. I would like to reference it, but I don't know if I should reference a paper or your git.
> 
> Bests,
> 
> B.

I did not use any reference. The methodology I chose was created by myself as a major project for one of my graduate classes. Although the stacking nature of a set predefined module of building blocks is well known for current literature for fixed length genomes. Although it was successful, this approach is highly outdated. The issue is that it does not allow for the model to expand or shrink passed the set boundaries (number of layers). These boundaries allow for differential evolution to be applied as it requires a fixed genome. I’d suggest looking at AmoebaNet, a much more sophisticated way at evolving convolutional neural Networks: https://arxiv.org/pdf/1802.01548.pdf
